/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/models/Room.gltf 
*/
import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export function Room(props) {
  const { nodes, materials } = useGLTF('models/Room.gltf')
  const texture = useTexture('textures/baked.jpg')
  texture.flipY = false;
  texture.encoding = THREE.sRGBEncoding;
  
  const textureMaterial = new THREE.MeshStandardMaterial({ map: texture })

  return (
    <group {...props} dispose={null}>
    <group name="Cabinet" position={[1.72, 0, -1.739]} rotation={[-3.137, -1.564, -3.137]} scale={0.878}>
      <group name="Draw" position={[0.098, 1.165, 0]} rotation={[-1.571, 0, -1.577]}>
        <mesh name="Draw_1" geometry={nodes.Draw_1.geometry} material={materials.Metal_1} />
        <mesh name="Draw_2" geometry={nodes.Draw_2.geometry} material={materials.Metal_Handle} />
        <mesh name="Draw_3" geometry={nodes.Draw_3.geometry} material={materials.Sticker} />
      </group>
      <group name="Draw001" position={[0.098, 0.794, 0]} rotation={[-1.571, 0, -1.577]}>
        <mesh name="Draw001_1" geometry={nodes.Draw001_1.geometry} material={materials.Metal_1} />
        <mesh name="Draw001_2" geometry={nodes.Draw001_2.geometry} material={materials.Metal_Handle} />
        <mesh name="Draw001_3" geometry={nodes.Draw001_3.geometry} material={materials.Sticker} />
      </group>
      <group name="Draw002" position={[0.098, 0.425, 0]} rotation={[-1.571, 0, -1.577]}>
        <mesh name="Draw002_1" geometry={nodes.Draw002_1.geometry} material={materials.Metal_1} />
        <mesh name="Draw002_2" geometry={nodes.Draw002_2.geometry} material={materials.Metal_Handle} />
        <mesh name="Draw002_3" geometry={nodes.Draw002_3.geometry} material={materials.Sticker} />
      </group>
      <group name="Draw003" position={[0.098, 0.055, 0]} rotation={[-1.571, 0, -1.577]}>
        <mesh name="Draw003_1" geometry={nodes.Draw003_1.geometry} material={materials.Metal_1} />
        <mesh name="Draw003_2" geometry={nodes.Draw003_2.geometry} material={materials.Metal_Handle} />
        <mesh name="Draw003_3" geometry={nodes.Draw003_3.geometry} material={materials.Sticker} />
      </group>
      <mesh name="Main_" geometry={nodes.Main_.geometry} material={materials.Metal_1} position={[0.042, 0.592, 0]} rotation={[-1.571, 0, -1.577]} />
    </group>
    <group name="Desk" position={[7.958, -0.033, -0.661]} rotation={[0, 1.553, 0]}>
      <group name="Keyboard" position={[-0.33, 0.957, -6.647]} rotation={[-1.579, 0.016, -3.138]} scale={25.291}>
        <mesh name="Keyboard|group1030983910|Dupli|22" geometry={nodes['Keyboard|group1030983910|Dupli|22'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group1075691498|Dupli|58" geometry={nodes['Keyboard|group1075691498|Dupli|58'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group1149852049|Dupli|53" geometry={nodes['Keyboard|group1149852049|Dupli|53'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group1152190519|Dupli|19" geometry={nodes['Keyboard|group1152190519|Dupli|19'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group1180881246|Dupli|50" geometry={nodes['Keyboard|group1180881246|Dupli|50'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group1238060299|Dupli|28" geometry={nodes['Keyboard|group1238060299|Dupli|28'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group1238428394|Dupli|61" geometry={nodes['Keyboard|group1238428394|Dupli|61'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group1272091893|Dupli|35" geometry={nodes['Keyboard|group1272091893|Dupli|35'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group1316349499|Dupli|39" geometry={nodes['Keyboard|group1316349499|Dupli|39'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group1323238240|Dupli|32" geometry={nodes['Keyboard|group1323238240|Dupli|32'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group145618305|Dupli|23" geometry={nodes['Keyboard|group145618305|Dupli|23'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group1486350934|Dupli|63" geometry={nodes['Keyboard|group1486350934|Dupli|63'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group150579309|Dupli|11" geometry={nodes['Keyboard|group150579309|Dupli|11'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group1529968652|Dupli|6" geometry={nodes['Keyboard|group1529968652|Dupli|6'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group1571332333|Dupli|33" geometry={nodes['Keyboard|group1571332333|Dupli|33'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group1581414308|Dupli|8" geometry={nodes['Keyboard|group1581414308|Dupli|8'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group1589752359|Dupli|26" geometry={nodes['Keyboard|group1589752359|Dupli|26'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group1629393722|Dupli|64" geometry={nodes['Keyboard|group1629393722|Dupli|64'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group1629609685|Dupli|21" geometry={nodes['Keyboard|group1629609685|Dupli|21'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group1675960081|Dupli|12" geometry={nodes['Keyboard|group1675960081|Dupli|12'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group1740918352|Dupli|46" geometry={nodes['Keyboard|group1740918352|Dupli|46'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group1753917514|Dupli|5" geometry={nodes['Keyboard|group1753917514|Dupli|5'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group1754683637|Dupli|40" geometry={nodes['Keyboard|group1754683637|Dupli|40'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group1764140354|Dupli|60" geometry={nodes['Keyboard|group1764140354|Dupli|60'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group1870575723|Dupli|65" geometry={nodes['Keyboard|group1870575723|Dupli|65'].geometry} material={materials['mat16.006']} />
        <mesh name="Keyboard|group1899843208|Dupli|36" geometry={nodes['Keyboard|group1899843208|Dupli|36'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group1956214489|Dupli|14" geometry={nodes['Keyboard|group1956214489|Dupli|14'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group196400395|Dupli|15" geometry={nodes['Keyboard|group196400395|Dupli|15'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group1976194690|Dupli|18" geometry={nodes['Keyboard|group1976194690|Dupli|18'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group205302596|Dupli|31" geometry={nodes['Keyboard|group205302596|Dupli|31'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group2074153597|Dupli|20" geometry={nodes['Keyboard|group2074153597|Dupli|20'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group2085389804|Dupli|57" geometry={nodes['Keyboard|group2085389804|Dupli|57'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group2091112366|Dupli|59" geometry={nodes['Keyboard|group2091112366|Dupli|59'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group2106755496|Dupli|4" geometry={nodes['Keyboard|group2106755496|Dupli|4'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group2146178072|Dupli|38" geometry={nodes['Keyboard|group2146178072|Dupli|38'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group252681800|Dupli|7" geometry={nodes['Keyboard|group252681800|Dupli|7'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group268332703|Dupli|44" geometry={nodes['Keyboard|group268332703|Dupli|44'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group287159489|Dupli|13" geometry={nodes['Keyboard|group287159489|Dupli|13'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group295085766|Dupli|9" geometry={nodes['Keyboard|group295085766|Dupli|9'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group311988427|Dupli|1" geometry={nodes['Keyboard|group311988427|Dupli|1'].geometry} material={materials['mat22.011']} />
        <mesh name="Keyboard|group34220672|Dupli|34" geometry={nodes['Keyboard|group34220672|Dupli|34'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group384612072|Dupli|10" geometry={nodes['Keyboard|group384612072|Dupli|10'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group418912012|Dupli|30" geometry={nodes['Keyboard|group418912012|Dupli|30'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group42243725|Dupli|37" geometry={nodes['Keyboard|group42243725|Dupli|37'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group425587018|Dupli|" geometry={nodes['Keyboard|group425587018|Dupli|'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group449779970|Dupli|3" geometry={nodes['Keyboard|group449779970|Dupli|3'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group45382983|Dupli|52" geometry={nodes['Keyboard|group45382983|Dupli|52'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group475225180|Dupli|41" geometry={nodes['Keyboard|group475225180|Dupli|41'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group573547017|Dupli|49" geometry={nodes['Keyboard|group573547017|Dupli|49'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group588539140|Dupli|47" geometry={nodes['Keyboard|group588539140|Dupli|47'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group601803475|Dupli|25" geometry={nodes['Keyboard|group601803475|Dupli|25'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group616518658|Dupli|56" geometry={nodes['Keyboard|group616518658|Dupli|56'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group687259746|Dupli|51" geometry={nodes['Keyboard|group687259746|Dupli|51'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group706802639|Dupli|17" geometry={nodes['Keyboard|group706802639|Dupli|17'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group729811280|Dupli|48" geometry={nodes['Keyboard|group729811280|Dupli|48'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group77921105|Dupli|42" geometry={nodes['Keyboard|group77921105|Dupli|42'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group790925258|Dupli|54" geometry={nodes['Keyboard|group790925258|Dupli|54'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group801095923|Dupli|29" geometry={nodes['Keyboard|group801095923|Dupli|29'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group806343109|Dupli|27" geometry={nodes['Keyboard|group806343109|Dupli|27'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group826580911|Dupli|24" geometry={nodes['Keyboard|group826580911|Dupli|24'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group873458270|Dupli|55" geometry={nodes['Keyboard|group873458270|Dupli|55'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group873558583|Dupli|62" geometry={nodes['Keyboard|group873558583|Dupli|62'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group877249531|Dupli|66" geometry={nodes['Keyboard|group877249531|Dupli|66'].geometry} material={materials['mat9.002']} />
        <mesh name="Keyboard|group954813675|Dupli|16" geometry={nodes['Keyboard|group954813675|Dupli|16'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group96314515|Dupli|2" geometry={nodes['Keyboard|group96314515|Dupli|2'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group96968687|Dupli|43" geometry={nodes['Keyboard|group96968687|Dupli|43'].geometry} material={materials['mat21.013']} />
        <mesh name="Keyboard|group993315105|Dupli|45" geometry={nodes['Keyboard|group993315105|Dupli|45'].geometry} material={materials['mat21.013']} />
      </group>
      <group name="Desk001" position={[-0.456, 0, -6.33]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
        <mesh name="Desk_1" geometry={nodes.Desk_1.geometry} material={materials.BlackCoatSteel} />
        <mesh name="Desk_2" geometry={nodes.Desk_2.geometry} material={materials.GrayPlastic} />
        <mesh name="Desk_3" geometry={nodes.Desk_3.geometry} material={materials.WhiteSteelScrew} />
        <mesh name="Desk_4" geometry={nodes.Desk_4.geometry} material={materials.BlackPlastic} />
        <mesh name="Desk_5" geometry={nodes.Desk_5.geometry} material={materials.BlackWood} />
      </group>
      <mesh name="Mouse001" geometry={nodes.Mouse001.geometry} material={materials['Material.001']} position={[-1.139, 0.942, -6.856]} rotation={[-Math.PI / 2, 0, -2.69]} />
      <mesh name="Mousepad001" geometry={nodes.Mousepad001.geometry} material={materials.Mousepad} position={[-1.132, 0.944, -6.86]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
    </group>
    <group name="PC" position={[1.377, 1.013, -0.777]} rotation={[0.015, -0.803, 0.036]} scale={1.536}>
      <mesh name="Computer" geometry={nodes.Computer.geometry} material={materials['Material.001']} position={[0.068, -0.059, -0.232]} rotation={[0.022, -0.802, 0.021]} />
    </group>
    <group name="Plant" position={[-1.656, 0.005, -1.782]} scale={2.009}>
      <group name="Houseplant_1" position={[0.057, -0.008, 0.08]} rotation={[-1.545, -0.034, -1.712]}>
        <mesh name="Houseplant_1_1" geometry={nodes.Houseplant_1_1.geometry} material={materials['Black.001']} />
        <mesh name="Houseplant_1_2" geometry={nodes.Houseplant_1_2.geometry} material={materials.Brown} />
        <mesh name="Houseplant_1_3" geometry={nodes.Houseplant_1_3.geometry} material={materials.Plant_Green} />
      </group>
    </group>
    <mesh name="bookcaseClosedDoors" geometry={nodes.bookcaseClosedDoors.geometry} material={materials.wood} position={[1.322, 0.004, 0.824]} rotation={[-1.985, 1.562, 1.978]} />
    <mesh name="bookcaseClosedDoors_1" geometry={nodes.bookcaseClosedDoors_1.geometry} material={materials.wood} position={[1.322, 0.004, 0.824]} rotation={[-1.985, 1.562, 1.978]} />
    <mesh name="Curtains" geometry={nodes.Curtains.geometry} material={materials['Mat.001']} position={[0.012, -0.008, -2.023]} />
    <group name="doorLeft" position={[1.322, 0.004, 0.824]} rotation={[-1.985, 1.562, 1.978]}>
      <mesh name="doorLeft_1" geometry={nodes.doorLeft_1.geometry} material={materials.wood} />
      <mesh name="doorLeft_1_1" geometry={nodes.doorLeft_1_1.geometry} material={materials.metal} />
    </group>
    <group name="doorRight" position={[1.322, 0.004, 0.824]} rotation={[-1.985, 1.562, 1.978]}>
      <mesh name="doorRight_1" geometry={nodes.doorRight_1.geometry} material={materials.metal} />
      <mesh name="doorRight_1_1" geometry={nodes.doorRight_1_1.geometry} material={materials.wood} />
    </group>
    <mesh name="Monitor" geometry={nodes.Monitor.geometry}  material={materials.Black} position={[1.789, 0.905, -0.408]} rotation={[0.406, -1.555, 0.403]} />
    <group name="Orchid" position={[1.871, 0.928, 0.374]}>
      <mesh name="Box003_1" geometry={nodes.Box003_1.geometry} material={materials['05___Default']} />
      <mesh name="Box003_1_1" geometry={nodes.Box003_1_1.geometry} material={materials['04___Default']} />
      <mesh name="Box003_1_2" geometry={nodes.Box003_1_2.geometry} material={materials['02___Default']} />
      <mesh name="Box003_1_3" geometry={nodes.Box003_1_3.geometry} material={materials['03___Default']} />
    </group>
    <group name="Orchid_Container" position={[1.871, 0.928, 0.374]}>
      <mesh name="GeoSphere001_1" geometry={nodes.GeoSphere001_1.geometry} material={materials['07___Default']} />
      <mesh name="GeoSphere001_1_1" geometry={nodes.GeoSphere001_1_1.geometry} material={materials.Material__289} />
    </group>
    <group name="Art" position={[2.032, 1.983, -0.139]} rotation={[1.762, 1.559, -0.192]}>
      <mesh name="Node-Mesh002" geometry={nodes['Node-Mesh002'].geometry} material={materials.mat23} />
      <mesh name="Node-Mesh002_1" geometry={nodes['Node-Mesh002_1'].geometry} material={materials.mat21} />
      <mesh name="Node-Mesh002_2" geometry={nodes['Node-Mesh002_2'].geometry} material={materials.mat7} />
      <mesh name="Node-Mesh002_3" geometry={nodes['Node-Mesh002_3'].geometry} material={materials.mat6} />
      <mesh name="Node-Mesh002_4" geometry={nodes['Node-Mesh002_4'].geometry} material={materials.mat17} />
      <mesh name="Node-Mesh002_5" geometry={nodes['Node-Mesh002_5'].geometry} material={materials.mat24} />
      <mesh name="Node-Mesh002_6" geometry={nodes['Node-Mesh002_6'].geometry} material={materials.mat25} />
    </group>
    <group name="OfficeChair" position={[0.73, 0.001, -0.499]} rotation={[-1.557, 0.044, 1.617]}>
      <mesh name="OfficeChair_1" geometry={nodes.OfficeChair_1.geometry} material={materials.Grey} />
      <mesh name="OfficeChair_2" geometry={nodes.OfficeChair_2.geometry} material={materials.Black} />
      <mesh name="OfficeChair_3" geometry={nodes.OfficeChair_3.geometry} material={materials.Chair} />
    </group>
    <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials.Wall} />
    <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials.Floor} />
    <mesh name="Plane_3" geometry={nodes.Plane_3.geometry} material={materials.Floor} />
  </group>
  )
}

useGLTF.preload('models/Room.gltf')
