/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/models/Room.gltf 
*/
import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export function Room(props) {
  const { nodes, materials } = useGLTF('models/Room.gltf')
  const texture = useTexture('textures/baked.jpg')
  texture.flipY = false;
  texture.encoding = THREE.sRGBEncoding;
  
  const textureMaterial = new THREE.MeshStandardMaterial({ map: texture })

  return (
    <group {...props} dispose={null}>
      <group position={[7.958, -0.033, -0.661]} rotation={[0, 1.553, 0]}>
        <group position={[-0.456, 0, -6.33]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes.Desk_1.geometry} material={materials.BlackCoatSteel} />
          <mesh geometry={nodes.Desk_2.geometry} material={materials.GrayPlastic} />
          <mesh geometry={nodes.Desk_3.geometry} material={materials.WhiteSteelScrew} />
          <mesh geometry={nodes.Desk_4.geometry} material={materials.BlackPlastic} />
          <mesh geometry={nodes.Desk_5.geometry} material={materials.BlackWood} />
        </group>
        <mesh geometry={nodes.Mouse001.geometry} material={materials['Material.001']} position={[-.8, 0.942, -6.6]} rotation={[-Math.PI / 2, 0, -2.69]} />
        <mesh geometry={nodes.Mousepad001.geometry} material={materials.Mousepad} position={[-.8, 0.944, -6.6]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
      </group>
      <group position={[1.377, 1.013, -0.777]} rotation={[0.015, -0.803, 0.036]} scale={1.536}>
        <mesh geometry={nodes.Computer.geometry} material={materials.Material} position={[0.068, -0.059, -0.232]} rotation={[0.022, -0.802, 0.021]} />
      </group>
      <group position={[-1.656, 0.005, -1.782]} scale={2.009}>
        <group position={[1.561, 0, 1.558]} rotation={[-1.545, -0.034, -1.712]}>
          <mesh geometry={nodes.Houseplant_1_1.geometry} material={materials['Black.001']} />
          <mesh geometry={nodes.Houseplant_1_2.geometry} material={materials.Brown} />
          <mesh geometry={nodes.Houseplant_1_3.geometry} material={materials.Plant_Green} />
        </group>
      </group>
      <group position={[1.237, 0.912, -.8]} rotation={[-2.639, 1.561, 2.648]} scale={2.10}>
        <mesh geometry={nodes.computerKeyboard_2.geometry} material={materials.metalDark} />
        <mesh geometry={nodes.computerKeyboard_2_1.geometry} material={materials.metalMedium} />
      </group>
      <group position={[1.237, 0.912, -.8]} rotation={[-2.639, 1.561, 2.648]} scale={2.10}>
        <mesh geometry={nodes.computerKeyboard_3.geometry} material={materials.metalMedium} />
        <mesh geometry={nodes.computerKeyboard_3_1.geometry} material={materials.metalDark} />
      </group>
      <mesh geometry={nodes.Cat.geometry} material={materials.Brown} position={[1.617, 0.378, -1.828]} rotation={[0.083, -1.014, 0.163]} scale={1.491} />
      <mesh geometry={nodes.Curtains.geometry} material={materials['Mat.001']} position={[0.012, -0.008, -2.023]} />
      <mesh geometry={nodes.Monitor.geometry} material={materials.lambert3SG} position={[1.789, 0.905, -0.408]} rotation={[0.406, -1.555, 0.403]} />
      <group position={[1.871, 0.928, 0.374]}>
        <mesh geometry={nodes.Box003_1.geometry} material={materials['05___Default']} />
        <mesh geometry={nodes.Box003_1_1.geometry} material={materials['04___Default']} />
        <mesh geometry={nodes.Box003_1_2.geometry} material={materials['02___Default']} />
        <mesh geometry={nodes.Box003_1_3.geometry} material={materials['03___Default']} />
      </group>
      <group position={[1.871, 0.928, 0.374]}>
        <mesh geometry={nodes.GeoSphere001_1.geometry} material={materials['07___Default']} />
        <mesh geometry={nodes.GeoSphere001_1_1.geometry} material={materials.Material__289} />
      </group>
      <group position={[2.032, 1.983, -0.139]} rotation={[1.762, 1.559, -0.192]}>
        <mesh geometry={nodes['Node-Mesh002'].geometry} material={materials.mat23} />
        <mesh geometry={nodes['Node-Mesh002_1'].geometry} material={materials.mat21} />
        <mesh geometry={nodes['Node-Mesh002_2'].geometry} material={materials.mat7} />
        <mesh geometry={nodes['Node-Mesh002_3'].geometry} material={materials.mat6} />
        <mesh geometry={nodes['Node-Mesh002_4'].geometry} material={materials.mat17} />
        <mesh geometry={nodes['Node-Mesh002_5'].geometry} material={materials.mat24} />
        <mesh geometry={nodes['Node-Mesh002_6'].geometry} material={materials.mat25} />
      </group>
      <group position={[0.73, 0.001, -0.499]} rotation={[-1.557, 0.044, 1.617]}>
        <mesh geometry={nodes.OfficeChair_1.geometry} material={materials.Grey} />
        <mesh geometry={nodes.OfficeChair_2.geometry} material={materials.Black} />
        <mesh geometry={nodes.OfficeChair_3.geometry} material={materials.Chair} />
      </group>
      <mesh geometry={nodes.Plane_1.geometry} material={materials.Wall} />
      <mesh geometry={nodes.Plane_2.geometry} material={materials.Floor} />
      <mesh geometry={nodes.Plane_3.geometry} material={materials.Floor} />
    </group>
  )
}

useGLTF.preload('models/Room.gltf')
